class_name StoryData
extends Resource

export (String, MULTILINE) var ticker_tape1_0 = (
	"BREAKING NEWS: PRESIDENT POLONIUS CALLS FOR "+
	"INCREASED BORDER SECURITY AFTER HORMONE BAN. " +
	"PRODUCTION OF WINDSOR AND FLOATER CLASS SHIPS TO INCREASE.")

export (String, MULTILINE) var ticker_tape1_1 = (
	"BREAKING NEWS: SKIRMISH AT BLOCKADE! " +
	"UNKNOWN ENEMY FORCE GETS PAST VETERAN " +
	"PILOTS. ALIEN SHIPS RESEMBLE OCEANIC " +
	"PREDATORS. SQUID CULT PRAISES QUICK RESPONSE.")
	
export (String, MULTILINE) var ticker_tape1_2 = (
	"BREAKING NEWS: PRESIDENT POLONIUS "+
	"ACCUSES SWEDES OF COLLABORATION WITH "+
	"PREDATOR INVADERS. SWEDISH PM SAYS "+
	"\"REALLY, MURT?\""
)

export (String, MULTILINE) var ticker_tape1_3 = (
	"BREAKING NEWS: TEMPORARY SETBACK AT THE "+
	"BORDER! VIOLENCE ERUPTS AFTER "+
	"ANNOUNCEMENT OF UNPRECEDENTED LOSS TO "+
	"FOREIGN PREDATORS. POLICE REASSURE "+
	"POPULACE THAT ALL IS UNDER CONTROL. "+
	"PRESIDENT POLONIUS REASSURES POPULACE "+
	"THAT SEVERAL CITIES ARE BURNING DOWN."
)

export (String, MULTILINE) var ticker_tape2_0 = (
	"BREAKING NEWS: NEW TECH DEPLOYED TO "+
	"BLOCKADE. INVADERS NOT EXPECTED TO "+
	"ADVANCE, SAYS PATROL. INVADERS BELIEVED "+
	"TO EAT CHILD SOULS, SAYS PRESIDENT. "+
	"OFFICIAL STATEMENT FROM GOVERNMENT: "+
	"\"NO THREAT IS POSED BY THE INCOMING "+
	"HORDES.\""
)

export (String, MULTILINE) var ticker_tape2_1 = (
	"BREAKING NEWS: FACT-CHECKERS INTRODUCE "+
	"NEW \"PANTS ON FIRE BUT EVEN WORSE "+
	"SOMEHOW\" RATING AFTER RECENT STATEMENTS "+
	"BY PRESIDENT POLONIUS. GOVERNMENT MAKES "+
	"FORMAL STATEMENT ACCUSING THE PROFESSION "+
	" OF FACT-CHECKER OF BEING LIKELY "+
	"PREDATORS, WHO FAILED SCHOOL, AND ALSO "+
	"WHINE A LOT."
)

export (String, MULTILINE) var ticker_tape2_2 = (
	"BREAKING NEWS: PRESIDENT POLONIUS DENIES "+
	"GENOCIDE ACCUSATIONS. GENOCIDE "+
	"ORGANIZING DEPARTMENT ASSURES POPULACE "+
	"OF GOOD INTENTIONS. \"WE ARE NOT PAVING "+
	"ANY ROADS, ESPECIALLY NOT TO HELL,\" SAYS "+
	"PARTY MAJORITY LEADER ABOUT G.O.D. |  "+
	"WORLD SANITY WATCHGROUP SAYS FORMER "+
	"CITIZEN ALEX DOE NOT ACTUALLY DEAD. "+
	"SQUID CULT SAYS WSW IS WRONG, ALSO "+
	"ACCUSES PREVIOUS ADMINISTRATION OF "+
	"NECROMANCY."
)

export (String, MULTILINE) var ticker_tape2_3 = (
	"BREAKING NEWS: MAJOR DEFEAT OF NAVY AT "+
	"DEEP LAYER OF BLOCKADE. ADDITIONAL "+
	"CARRIERS DEPLOYED TO REGION. PRESIDENT "+
	"AND PRESIDENT'S REP RELEASE SIMULTANEOUS "+
	"STATEMENTS: \"THOUSANDS OF PREDATORY "+
	"INVADERS! MUST BE STOPPED, MUST PREVENT "+ 
	"ALL SURGICAL ATTACKS, ALL HORMONES. WE "+
	"WILL USE THE BEST, THE BEST SHIPS AND "+
	"KILL THEM ALL.\" \"A SINGULAR SMALL SHIP "+
	"IS BELIEVED TO BE THE CULPRIT BEHIND THE "+
	"MINOR ATTACKS WE'VE BEEN SEEING. WE DO "+
	"NOT EXPECT MUCH OF A THREAT FROM THEM.\""
)

export (String, MULTILINE) var ticker_tape3_0=(
	"BREAKING NEWS: RIOTS OVER LACK OF ACCESS "+
	"TO SO-CALLED \"GENDER AFFIRMING CARE\" OCCURRING ACROSS "+
	"PLANET. IT IS BELIEVED THAT ALEX DOE'S "+
	"REPORTED SURVIVAL AND POSSIBLE PRESENCE "+
	"ON PREDATOR SHIP STOKING FLAMES."
)

export (String, MULTILINE) var ticker_tape3_1=(
	"BREAKING NEWS: PER COURT ORDER, WE AT "+
	"BREAKING NEWS NEWS MEDIA MUST STATE THAT "+
	"THE AFOREMENTIONED \"GENDER AFFIRMING CARE\" IS "+
	"ACTUALLY BASIC MEDICAL CARE. ALSO, THE "+
	"PRESIDENT IS A LIAR, THIS CHANNEL IS "+
	"LIES, AND FUCK ALL OF YOU WHO CAN'T DEAL "+
	"WITH PEOPLE WHO ARE SLIGHTLY DIFFERENT "+
	"THAN YOU. SINCERELY, THE PERSON FORMERLY "+
	"IN CHARGE OF WRITING THESE STUPID "+
	"NEWS ALERTS, WHO IS COUNTING THIS AS HIS "+
	"- ER, HER - FORMAL "+
	"NOTICE OF RESIGNATION."
)

export (String, MULTILINE) var ticker_tape3_2 = (
	"BREAKING NEWS: BREAKING NEWS NEWS MEDIA "+
	"UNDER NEW OWNERSHIP. ANTI-HORMONE LAWS "+
	"REVERSED AFTER PRESIDENT POLONIUS FORCED "+
	"TO RESIGN, FOLLOWING LOSING HIS HAIR "+
	"DUE TO HORMONAL PROBLEMS. BLOCKADE "+
	"REMOVAL UNDERWAY FOLLOWING RESTRUCTURING "+
	"OF BORDER PATROL POLICY AFTER 95% FIRED "+
	"FROM AGENCY. | ALEX DOE FOUND ALIVE, "+
	"COINCIDENTALLY IN AN UNDERGROUND "+
	"HOSPITAL FOUND TO BE DISTRIBUTING "+
	"NECESSARY MEDICAL SUPPLIES. NO CRIMINAL "+
	"CHARGES BEING PURSUED BY GOVERNMENT. | "+
	"G.O.D. SHUT DOWN BY PRESIDENT DIOL ON DAY 1. "+
	"\"WHY DO WE EVEN NEED A GENOCIDE "+
	"DEPARTMENT? GENOCIDES ARE BAD,\" SAYS "+
	"PRESIDENT DIOL. \"CAN'T SAY I'M A FAN OF "+
	"MURDER IN GENERAL, REALLY,\" XE SAID IN "+
	"FOLLOW-UP INTERVIEW."
)
